# controllers:
#     resource: ../src/Controller/
#     type: attribute
app_lucky_number:
    path: /convert/number
    controller: App\Controller\ConvertController::readNumber
app_get_lanuages:
    path: /get/languages
    controller: App\Controller\ConvertController::getLanguages
